### PR TITLE
code to find the last digit of a number

### PR DESCRIPTION
**Pull request by biru-codeastromer**
hey ,here the problem is as follows : Given an integer N print the last digit of the given integer.
in solution i used the modulo to find the last digit using python..hope to get pr accepted and get hacktoberfest label..thanks

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot.

**Comment by biru-codeastromer** [comment]
okay please take this @Ayu-hack 
Screenshot 2024-10-17 at 3 32 06 PM

**Comment by Ayu-hack** [comment]
which platform? 
it is not geeksforgeeks

**Comment by Ayu-hack** [comment]
Screenshot 2024-10-17 at 6 52 07 PM

remove the second code file and re create new PR

**Pull request closed without merging**
