### PR TITLE
Added 'Total Count' Solution of GFG 29th Sept POTD

### PR DESCRIPTION
**Pull request by labishbardiya**
This is the solution of the Geeks for Geeks, 'Problem of the day' of 29th September 2024 in Python language. Please add `good first issue` and `hacktoberfest` labels.

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot of working

**Comment by labishbardiya** [comment]
Screenshot 2024-10-08 094158

**Comment by Ayu-hack** [comment]
Merged.

### Thank you for contributing .

Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by labishbardiya** [comment]
Please provide `good first issue` label if possible.

**Comment by Ayu-hack** [comment]
Good first issue is for new newcomers brother.

**Pull request merged**
