### PR TITLE
Language Translator added

### PR DESCRIPTION
**Pull request by Aishika3**
` Language Translator ` 

The Language Translator web page allows learners to change the language of user input. This feature fosters language exploration and facilitates understanding by providing translations across various languages.It prioritizes user experience with a dynamic Light and Dark Mode Toggling feature. Users can seamlessly switch between light and dark themes, enhancing visual comfort and flexibility during usage of this application. This aesthetic customization ensures a pleasant interface tailored to individual preferences.

` Installations `

   API used:-https://mymemory.translated.net/doc/spec.php (MyMemory Translation api)

` The screenshot of the above is attached below `

Language Translator

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the working video

**Comment by Aishika3** [comment]
**The working video of the above is attached below **

https://github.com/user-attachments/assets/0eab40d6-11a6-44d6-b513-c6572cef37f1

**Comment by Aishika3** [comment]
Working link :-
` https://translatorforlanguage.netlify.app/ `

**Comment by Ayu-hack** [comment]
Great Work! 
Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on GitHub and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Pull request merged**
