### PR TITLE
Longest Common Prefix of Strings

### PR DESCRIPTION
**Pull request by stutimi**
gfg30july
gfg30julyq

### CODE REVIEW

**Comment by Ayu-hack** [comment]
In this you have added the file in FOLDER but you have added 2 more file idk why and that do in MAIN FOLDER. Please rest two files

**Comment by stutimi** [comment]
Done

**Comment by stutimi** [comment]
> In this you have added the file in FOLDER but you have added 2 more file idk why and that do in MAIN FOLDER. Please rest two files

done, can you plz check

**Comment by Ayu-hack** [comment]
Now fine !

**Comment by Ayu-hack** [comment]
Make the more PRs like this onwards

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by stutimi** [comment]
> Make the more PRs like this onwards

ok

**Pull request merged**
