### PR TITLE
Added GeeksForGeeks Problem of the Day for 14 OCT 2024

### PR DESCRIPTION
**Pull request by Kanishk-03-Jain**
I have added the problem of the day of 14 Oct 2024 on GeeksForGeeks. 
I have also included the Driver code (taking input and printing output) so the code can run independently

### CODE REVIEW

**Comment by Kanishk-03-Jain** [comment]
@Ayu-hack please review this request and suggest any changes

**Comment by Ayu-hack** [comment]
PLEASE DONT SPAM, MAKE PRs in few hours of intervals

**Comment by Kanishk-03-Jain** [comment]
image
image


> Please share the screenshot.

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Pull request merged**
