### PR TITLE
Create Missing And Repeating(23 sep GFG-POTD)

### PR DESCRIPTION
**Pull request by Anshuman7080**
Screenshot 2024-10-14 062803
Screenshot 2024-10-14 062816
Screenshot 2024-10-14 062831

### CODE REVIEW

**Comment by Anshuman7080** [comment]
This code defines a function that identifies a duplicate element (B) and the missing element (A) in an array of integers where elements range from 1 to n. It sorts the array and checks for discrepancies between consecutive elements to determine both the duplicate and the missing values, returning them in a vector.


Please ,assign me this.

**Comment by Ayu-hack** [comment]
Already exists but language is different. So accepting .

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
Brother you have the added files in MAIN . You were supposed to ADD IN RESPECTIVE FOLDERS.

**Pull request merged**
