### PR TITLE
Added emoji Generator

### PR DESCRIPTION
**Pull request by ExPl0iT-29**
Added my mini project!
Random Emoji Generator.
Thankyou ! 

Screenshot of Emoji Generator:
Emoji_generator

### CODE REVIEW

**Comment by ExPl0iT-29** [comment]
Hey,
which else screenshot should i upload?
#145

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on [GitHub](https://github.com/Ayu-hack) and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Comment by ExPl0iT-29** [comment]
Thanks i requested a connection on LinkedIn.
Great Experience Thankyou <3

**Pull request merged**
