### PR TITLE
Diabetes Prediction System

### PR DESCRIPTION
**Pull request by dvamsidhar2002**
Hey! I have a added a new machine learning project which is "Diabetes Prediction System". Do consider the project and merge it if you like it.

The following is the screenshot of the final testing of the project.
image

Regards,
D Vamsidhar

### CODE REVIEW

**Comment by Ayu-hack** [comment]
you can make user defined .

**Comment by Ayu-hack** [comment]
rather entering the input earlier. it should ask the user to enter the reading and then give the result.

**Comment by dvamsidhar2002** [comment]
Hey Ayush! Thank you very much for the suggestion. Keeping them in mind I have updated the code and made the changes. Do consider the changes and merge it if you like it.

The following is the screenshot of the updated code.
image

image

Regards,
D Vamsidhar

**Comment by Ayu-hack** [comment]
Amazing Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on [GitHub](https://github.com/Ayu-hack) and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Comment by dvamsidhar2002** [comment]
Sure! Do follow me on [GitHub ](https://github.com/dvamsidhar2002)and [LinkedIn ](https://www.linkedin.com/in/dvamsidhar5932200802/)if you want to see updates regarding the other projects I am working on.

**Pull request merged**
