### PR TITLE
added amazonclone backend

### PR DESCRIPTION
**Pull request by Kirtishukla2004**

### CODE REVIEW

**Review by Ayu-hack — COMMENTED** [review]
Please share the screenshot of working or page.

**Comment by Ayu-hack** [comment]
Please the add this project in Mini-Project Folder.

**Comment by Ayu-hack** [comment]
Please share the screenshot of working or page.

**Comment by Kirtishukla2004** [comment]
i have added the link file to view working project

**Comment by Ayu-hack** [comment]
where is the link ? you have created new PR with 1500+ and this PR contains 5000+ files.

**Pull request merged**
