### PR TITLE
adding GFG POTD 24-02-2024 Maximum Sum Problem

### PR DESCRIPTION
**Pull request by keikurono7**
image

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please add file in respective FOLDER

**Comment by keikurono7** [comment]
it is a february problem so i've added it to feb folder. Is smtg wrong?

**Comment by Ayu-hack** [comment]
no worries. I have checked its correct!

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on [GitHub](https://github.com/Ayu-hack) and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Pull request merged**
