### PR TITLE
Single Element Among Triplets (4th january solution)

### PR DESCRIPTION
**Pull request by taneeshamadhu18**
4th january solution
Single Element Among Triplets

### CODE REVIEW

**Comment by taneeshamadhu18** [comment]
Screenshot (103)

**Comment by taneeshamadhu18** [comment]
@Ayu-hack please merge the pr

**Comment by taneeshamadhu18** [comment]
add the hacktoberfest labels

**Comment by Ayu-hack** [comment]
You are solving POTD of January and pushing files in February and march. What's wrong?

Screenshot 2024-10-19 at 8 08 55 PM

**Comment by taneeshamadhu18** [comment]
closest neighbour is of march
single among triplet is of january

**Pull request closed without merging**
