### PR TITLE
Delete Alternate Nodes

### PR DESCRIPTION
**Pull request by stutimi**
gfgdncpp
gfg2
gfg3
Description: This code deletes alternate nodes in a singly linked list, starting from the second node, by adjusting the next pointers and freeing memory. It also includes a utility function to print the list.

Kindly assign me this.

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Great you learnt it !

**Comment by Ayu-hack** [comment]
You need only attached that first screenshot which the complete page. You should make more PR.

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on GitHub and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Comment by stutimi** [comment]
Thank you!!
Can I make more reprosetry like this? LeetCode and gfg both and add this on
that folder .

**Comment by Ayu-hack** [comment]
Yes you can!

**Comment by stutimi** [comment]
Okay ,thank you!!

**Pull request merged**
