### PR TITLE
Solution for "Geek and its Game of Coins" (29 May)

### PR DESCRIPTION
**Pull request by SaurabhKumar171**
**Title : Geek and its Game of Coins**

**Description :** 
This PR adds a dynamic programming solution to the "Geek and its Game of Coins" problem, where players take turns picking x, y, or 1 coin, and Geek plays first. It determines if Geek will win when both play optimally. The PR also includes a driver program that takes inputs for n, x, and y, and outputs whether Geek wins or not.

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot of working and mention the date of problem

**Comment by SaurabhKumar171** [comment]
Hey @Ayu-hack , Please find below the date and screenshot of running code for your refrence.

GFG POTD - 29 May

**Title : Geek and its Game of Coins**
Screenshot 2024-10-12 at 9 33 06 AM

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by SaurabhKumar171** [comment]
Thank you so much for the opportunity! 😄
I'm glad I could contribute, and I truly appreciate your support. I'll definitely tag you in my Hacktoberfest certificate and badges post on LinkedIn! 🙌

Already following your GitHub, and I've just sent a connection request on LinkedIn. Looking forward to staying connected and collaborating on more projects!

Best of luck with your work, and thanks again! 🚀

**Comment by Ayu-hack** [comment]
You're very welcome! 😄

**Pull request merged**
