### PR TITLE
Create odd even problems gfg june

### PR DESCRIPTION
**Pull request by Mrdanish24**
Given a string s of lowercase English characters, determine whether the summation of x and y is EVEN or ODD. where:

x is the count of distinct characters that occupy even positions in the English alphabet and have even frequency.  y is the count of distinct characters that occupy odd positions in the English alphabet and have odd frequency. Ex: string = "ab" here 'a' has an odd(1) position in the English alphabet & has an odd(1) frequency in the string so a is odd but b has an even(2) position in the English alphabet & has odd(1) frequency so it doesn't count(since string doesn't have 2 b's) so the final answer x + y = 1+0 = 1(odd) would be "ODD".

Note:

Return "EVEN" if the sum of x & y is even otherwise return "ODD". You need to find index of characters in the english alphabet "abcdefghijklmnopqrstuvwxyz". Examples :

Input: s = "abbbcc"
Output: ODD
Explanation: x = 0 and y = 1 so (x + y) is ODD. 'a' occupies 1st place(odd) in english alphabets and its frequency is odd(1), 'b' occupies 2nd place(even) but its frequency is odd(3) so it doesn't get counted and 'c' occupies 3rd place(odd) but its frequency is even(2) so it also doesn't get counted.

Screenshot 2024-10-17 230512

### CODE REVIEW

**Comment by Mrdanish24** [comment]
please assign me

**Comment by Ayu-hack** [comment]
Brother always write file extension.

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Mrdanish24** [comment]
ok sir

**Pull request merged**
