### PR TITLE
Added solution of POTD 25th of May in C++

### PR DESCRIPTION
**Pull request by horrible-hacker**
Added Solution of POTD 25th of May
Regarding : (Add solution of May 2024. #16)

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot of working and comment in respective issues as well.

**Comment by horrible-hacker** [comment]
Screenshot 2024-10-11 at 10 33 31 PM
I have attached the screenshot of the above solution.

**Comment by Ayu-hack** [comment]
Great Work! 
Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on GitHub and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)! as a token of appreciation for the efforts! 🙌

**Pull request merged**
