### PR TITLE
Solution Odd Even Problem (01 July).java

### PR DESCRIPTION
**Pull request by Samruddhi345A**
#17 added GF POTD 01-06-2024 in java

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot.

**Comment by Ayu-hack** [comment]
Please mention the problem name with date

**Comment by Samruddhi345A** [comment]
issue : #17
Problem name : Odd Even Problem
Date: 01 June, 2024
Attached the screenshots below:
jume01_06_2024(1)
june01_06_2024

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Pull request merged**
