### PR TITLE
30 April 2024 problem: Add Number LinkedList in java issue #15

### PR DESCRIPTION
**Pull request by skanarul8002**
**Add** Number Linked Lists
Difficulty: Medium Points: 4
Given two numbers, num1, and num2, represented by linked lists. The task is to return the head of the linked list representing the sum of these two numbers.

For example, the number 190 will be represented by the linked list, 1->9->0->null, similarly 25 by 2->5->null. Sum of these two numbers is 190 + 25 = 215, which will be represented by 2->1->5->null. You are required to return the head of the linked list 2->1->5->null.

Note: There can be leading zeros in the input lists, but there should not be any leading zeros in the output list.

**Examples:**

Input: num1 = 45 (4->5->null), num2 = 345 (3->4->5->null)
Output:  3->9->0->null  
 
**Explanation:** 
For the given two linked list (4 5) and (3 4 5), after adding the two linked list resultant linked list will be (3 9 0).

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot of working here.

**Comment by skanarul8002** [comment]
> Please share the screenshot of working here. Done #86 
image

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on GitHub and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)  as a token of appreciation for the efforts! 🙌

**Pull request merged**
