### PR TITLE
Oct 8 GFG POTD

### PR DESCRIPTION
**Pull request by bastenahamad**
Modified the code and wrote code that runs in o(n) as asked in the question. The Previous Solution was of O(nlogn) which is slower than o(n).
Kindly Review it and Merge it under the Hacktoberfest2024 tags.
Thank You <3

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot.

**Comment by bastenahamad** [comment]
image
image

My code visits each array element one times which makes it O(n) time complexity

**Comment by bastenahamad** [comment]
I have attached screenshots. Kindly Check and merge it with
the hacktoberfest tags.
Thank You.

**Comment by Ayu-hack** [comment]
Great!
Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Pull request merged**
