### PR TITLE
Added Snake Game

### PR DESCRIPTION
**Pull request by SyedShagufta**
**Snake Game** 

- This is a classic Snake game where the player controls a snake using the arrow keys. 
- The objective is to eat the food that appears on the screen to grow longer and increase your score but the game ends if the snake collides with the walls or with its own body. 
- It's a fun and engaging way to test your reflexes and see how long you can survive as the snake gets longer and faster!

* The Snake Game is developed using Python and the Turtle Graphics library.

**Demo of Working**

https://github.com/user-attachments/assets/0c6cc02b-9079-4c21-b2a9-f79bcf6de71b

### CODE REVIEW

**Comment by Ayu-hack** [comment]
please comment in respective issues as well.

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
f possible do follow on GitHub and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)! as a token of appreciation for the efforts! 🙌

**Comment by SyedShagufta** [comment]
Sure, Will be glad to connect 😊

**Pull request merged**
