### PR TITLE
Book_My_Show_clone

### PR DESCRIPTION
**Pull request by Rockyoudead8**
working

### CODE REVIEW

**Comment by Rockyoudead8** [comment]
hey buddy you said to make some advanced project is this good ? if yes plzz merge it

**Comment by Ayu-hack** [comment]
Please share the screenshot of webpage

**Comment by Ayu-hack** [comment]
@Rockyoudead8 great project buddy

**Comment by Rockyoudead8** [comment]
image

**Comment by Rockyoudead8** [comment]
done sir

**Comment by Ayu-hack** [comment]
buddy you can improve it bit more

**Comment by Rockyoudead8** [comment]
can you suggest some ideas that will be more than helpful

**Comment by Ayu-hack** [comment]
It is looking too basic buddy, enhance it bit more .

**Review by Ayu-hack — COMMENTED** [review]
Enhancement requested.

**Comment by Rockyoudead8** [comment]
ok sir worknig on it

**Comment by Ayu-hack** [comment]
@Rockyoudead8 Okay buddy !
Should I close this PR now or you will provide enhancement soon ?

**Comment by Rockyoudead8** [comment]
working sir doing a new commit ASAP

**Comment by Ayu-hack** [comment]
@Rockyoudead8 okay! Great

**Comment by Rockyoudead8** [comment]
done sir kindly look into it

**Comment by Rockyoudead8** [comment]
now i have also added 2 sections named bollywood and holywood and created a effect such that whenever i hover over them then only the movies contained in it are shown

image

**Comment by Ayu-hack** [comment]
@Rockyoudead8 buddy please do the alignment properly. It looks that good.

**Comment by Rockyoudead8** [comment]
Doing sir

**Comment by Ayu-hack** [comment]
Use CSS OR React JS to enhance

**Comment by Rockyoudead8** [comment]
sir commited have a look

**Comment by Rockyoudead8** [comment]
sir i want to add more mini projects like pdf extraction tool then where i can submit them to create a new pull request

**Comment by Ayu-hack** [comment]
Brother please share screenshot of web page first

**Comment by Rockyoudead8** [comment]
image

**Comment by Rockyoudead8** [comment]
bollywood and hollywood sections are clickable
means they will drop down and show the movies when clicked

**Comment by Rockyoudead8** [comment]
sir wait a sec enhancing it more

**Comment by Rockyoudead8** [comment]
done its my final code

**Comment by Rockyoudead8** [comment]
kindly merge now if possible

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Rockyoudead8** [comment]
sir for new projects can i submit it here to create a new pull request ? eg like pdf extraction tool and digital whitboard using tkinter which can be used as for drawing or some explanation

**Comment by Ayu-hack** [comment]
yes you can add new projects but bring something new and unique, advance  These are projects are too basic and common.

**Comment by Rockyoudead8** [comment]
Sir can you suggest some projects as I am not getting what to make ?

**Comment by Ayu-hack** [comment]
find some good n advance.

**Pull request merged**
