### PR TITLE
Create Majority Vote(3 oct GFG-POTD)

### PR DESCRIPTION
**Pull request by Anshuman7080**
This code defines a class Solution with a method findMajority that identifies elements in a vector nums appearing more than n/3 times, where n is the size of the vector. It uses an unordered map to count occurrences of each element, then collects elements meeting the frequency condition into a result vector, which is sorted before being returned. If no such elements exist, it returns {-1}.

Please assign me this.

### CODE REVIEW

**Comment by Anshuman7080** [comment]
Screenshot 2024-10-14 065325
Screenshot 2024-10-14 065331
Screenshot 2024-10-14 065318

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on [GitHub](https://github.com/Ayu-hack) and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Comment by Anshuman7080** [comment]
> if possible do follow on [GitHub](https://github.com/Ayu-hack) and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

Already following on Linkedin

**Comment by Ayu-hack** [comment]
Brother you have the added files in MAIN . You were supposed to ADD IN RESPECTIVE FOLDERS.

**Pull request merged**
