### PR TITLE
Medical Insurance Cost Predictor

### PR DESCRIPTION
**Pull request by dvamsidhar2002**
I have added a new machine learning project that is "Medical Insurance Cost Predictor". Do consider the project and merge it if you like it. Please give me any suggestions if required.

This is the screenshot of the project testing
image

Output:
image

Regards,
D Vamsidhar

### CODE REVIEW

**Comment by Ayu-hack** [comment]
what is the use of region in medical insurance cost prediction? please define.

**Comment by Ayu-hack** [comment]
the project was created on February 2023. It seems to be copied from somewhere.

**Comment by dvamsidhar2002** [comment]
Hey! this is one of my old projects which I worked on when I was learning about ML. I did took help of youtube videos as I was learning at that time. 

And regarding the use of region feature.  Region is a crucial feature when it comes to healthcare costs because the factors which effect the costs are healthcare accessibility, lifestyle based on region like if the region is a metropolitan city there is a chance the primary beneficiary has sedentary lifestyle which definitely effects healthcare costs. Keeping this in mind I included this feature.

**Comment by Ayu-hack** [comment]
Okay. Please replace the number options with text for better clarity. For example, instead of showing sex: 0, display male or female, and instead of region: 3, show northeast. This will make the output easier to understand and more user-friendly.

**Comment by dvamsidhar2002** [comment]
Committed the changes in the code as suggested. Thanks for the suggestion.

image

Regards,
D Vamsidhar

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on [GitHub](https://github.com/Ayu-hack) and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Pull request merged**
