### PR TITLE
Create Kadane's Algorithm(6 sep GFG-POTD)

### PR DESCRIPTION
**Pull request by Anshuman7080**
Screenshot 2024-10-14 060856

Screenshot 2024-10-14 060832

Screenshot 2024-10-14 060840

### CODE REVIEW

**Comment by Anshuman7080** [comment]
This code implements a function that calculates the maximum sum of contiguous subarrays using Kadane's algorithm. It iterates through the array, maintaining a running sum (prefix) and updating the maximum sum (maxi) whenever the current sum exceeds the previous maximum, resetting the sum to zero when it becomes negative.


Kindly,assign me this.

**Comment by Ayu-hack** [comment]
Already exists.

**Comment by Ayu-hack** [comment]
Please provide solutions of potd those solution isn't available in repo, you can give solutions of months like January or February, see in which few solutions are there.

**Comment by Ayu-hack** [comment]
PLEASE MAKE PRs IN FEW HOURS OF INTERVAL, DONT SPAM AT ONCE. 
PLEASE TRY TO UNDERSTAND.

**Pull request closed without merging**
