### PR TITLE
Solved Oct 12 Problem using Python

### PR DESCRIPTION
**Pull request by SWM32**
Solved Two Smallests in Every Subarray(Oct 12) problem using python

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot.

**Comment by SWM32** [comment]
Hello Sorry I couldn't upload the screen shots earlier. I also completed another problem. Oct 19 problem using python I'll provide the SS in both problems.
 
Oct 12 Problem
Screenshot 2024-10-23 173445

Oct  19 Problem
Screenshot 2024-10-23 172558

**Comment by Ayu-hack** [comment]
1 PR = 1 Solution. 
Please remove other solution.

**Comment by SWM32** [comment]
Ok I'll remove the most recent commit

**Comment by SWM32** [comment]
I removed the Oct 19 problem commit. Is it ok to commit it in a different PR?

**Comment by Ayu-hack** [comment]
okay.create new PR

**Comment by SWM32** [comment]
@Ayu-hack Could you please add hactober label to this PR.(For the Oct 12 problem). I'll add Oct 19 problem in a different PR

**Comment by Ayu-hack** [comment]
@SWM32 assigned.

**Pull request closed without merging**
