### PR TITLE
Create Leetcode WC-413 September 1st  KthNearestObstacleQueries.cpp

### PR DESCRIPTION
**Pull request by Sri5275**
**Issue**
* #19 
image

### CODE REVIEW

**Comment by Sri5275** [comment]
Hey @Ayu-hack ,this PR is ready for review.

**Comment by Ayu-hack** [comment]
please mention date of solution

**Comment by Sri5275** [comment]
Hey @Ayu-hack ,Added the date of solution.

**Comment by Ayu-hack** [comment]
Great Work !
Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Pull request merged**
