### PR TITLE
SUM OF PRODUCT (12-04-2024)

### PR DESCRIPTION
**Pull request by Rockyoudead8**
Sum_Of_Products(12-04-2024)

### CODE REVIEW

**Comment by Ayu-hack** [comment]
please mention problem name in title with date

**Comment by Rockyoudead8** [comment]
ok sir

**Comment by Ayu-hack** [comment]
Buddy please add only 1 solution at a time. Please try to understand.

**Comment by Rockyoudead8** [comment]
ok sir my bad

**Comment by Rockyoudead8** [comment]
sir can you help me with this i am not getting how to edit the image can you consider it in the way it is i am new to github so i am not getting how to delete this commit

**Comment by Rockyoudead8** [comment]
if i will try to solve it ,it will only spoil the current situation

**Comment by Rockyoudead8** [comment]
i will make sure it doesnt happen onwards

**Comment by Rockyoudead8** [comment]
DONE SIR

**Comment by Rockyoudead8** [comment]
sir kindly ignore the other commits it was done by mistake

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on GitHub and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Pull request merged**
