### PR TITLE
GFG sol PODT of 1 nov 24 in py

### PR DESCRIPTION
**Pull request by thedarkking01**
@Ayu-hack Hii 😊
pic: 
image
image

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on [GitHub](https://github.com/Ayu-hack) and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Comment by Ayu-hack** [comment]
same thing you have done here as well. by mistake I have merged it too. I will delete the file from here create 2 pr with correct details.

**Comment by thedarkking01** [comment]
okay

**Pull request merged**
