### PR TITLE
Added POTD for 8 October 2024

### PR DESCRIPTION
**Pull request by LeViiAcKerMan01**

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot.

**Comment by Ayu-hack** [comment]
You can give solution of previous potd.

**Comment by LeViiAcKerMan01** [comment]
> Please share the screenshot.



Solution was accepted successfully!

**Comment by LeViiAcKerMan01** [comment]
Please merge thisone, i am ready to give the solution to the previous one aswell.. But it is already there so, should i provide solution in cpp only!!

**Comment by Ayu-hack** [comment]
Merged. Yes you can provide solutions in any language. Choose any open issue even you can add projects .

**Comment by LeViiAcKerMan01** [comment]
Thnc buddy...

**Pull request merged**
