### PR TITLE
 Panagram _Checking_(1 FEB  GFG POTD)

### PR DESCRIPTION
**Pull request by Anshv9616**
The code checks if a given string s contains every letter of the English alphabet at least once, making it a pangram.

Step-by-Step Breakdown
Initialize Vector:
vector<int> ans(26, 0);

A vector ans of size 26 is initialized to zero. Each index of this vector corresponds to a letter of the English alphabet (0 for ‘A’/‘a’, 1 for ‘B’/‘b’, …, 25 for ‘Z’/‘z’). Count Letters:
for (int i = 0; i < s.length(); i++) {
    char ch = s[i];
    if (ch >= 65 && ch <= 90) 
        ans[ch - 'A']++;
    else if (ch >= 97 && ch <= 122)
        ans[ch - 'a']++;
}

The code iterates through each character in the string s. It checks if the character is an uppercase letter (A-Z) using ASCII values (65 to 90). If true, it increments the corresponding index in the ans vector. Similarly, it checks if the character is a lowercase letter (a-z) using ASCII values (97 to 122). If true, it increments the corresponding index in the ans vector. Check Completeness:
for (int i = 0; i < 26; i++) {
    if (ans[i] == 0) return false;
}
return true;

After counting the letters, the code checks if all elements in the ans vector are greater than zero. If any element is zero, it means that particular letter is missing from the string, and the function returns false. If all elements are non-zero, it returns true, indicating that the string is a pangram.

### CODE REVIEW

**Comment by Anshv9616** [comment]
Screenshot 2024-10-18 064251
Screenshot 2024-10-18 064302
Screenshot 2024-10-18 064241

**Comment by Ayu-hack** [comment]
Please rename the file and write file extension

**Comment by Ayu-hack** [comment]
Please REF to README ONCE.

**Comment by Ayu-hack** [comment]
file extension missing

**Comment by Ayu-hack** [comment]
Closed due to no response

**Pull request closed without merging**
