### PR TITLE
Issue #18 has resolved.

### PR DESCRIPTION
**Pull request by Ananyajain2004**
POTD 25 sep in cpp added successfully. 

using two approaches:
1.) using reverse function and slow & fast pointers
2.) using stack

please take a time to review and merge it.

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot.

**Comment by Ananyajain2004** [comment]
1.) using  reverse function 

Screenshot (41)
Screenshot (43)
Screenshot (44)
Screenshot (45)



2.) using stack
Screenshot (42)
Screenshot (46)

**Comment by Ayu-hack** [comment]
Please send screenshot of geeksforgeeks output window. 

EXP:-
Screenshot 2024-10-23 at 6 39 29 PM

**Comment by Ananyajain2004** [comment]
Screenshot (47)

Screenshot (48)

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on [GitHub](https://github.com/Ayu-hack) and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Pull request merged**
