### PR TITLE
Create Longest Common Prefix of Strings(31 july gfg potd)

### PR DESCRIPTION
**Pull request by AnuragMishra358**
Function: longestCommonPrefix
Input: A vector arr of strings.
Output: A string representing the longest common prefix shared by all strings in the input vector, or "-1" if no common prefix exists. Key Steps:
Find the Shortest String in the Array:

The loop for(int i=0; i<n; i++) traverses the vector to find the string with the minimum length (minlen) and stores its index in idx. This is done to limit comparisons only up to the length of the shortest string. Compare Characters Column by Column:

For each character position i (from 0 to minlen-1) in the shortest string (retrieved using arr[idx]), the code extracts a single-character substring (substring). It then compares this character across all strings in the vector. If all strings have the same character at position i, it is added to the result ans. If any string does not match the character, the loop breaks, as no further common prefix can exist beyond this point. Return the Result:

If a common prefix is found, it is stored in the string ans. If no common prefix exists (ans remains an empty string), the method returns "-1". Example:
If the input vector is ["flower", "flow", "flight"], the longest common prefix is "fl". If the input is ["dog", "racecar", "car"], the method returns "-1", as there is no common prefix. Edge Cases:
If the input array is empty, the function will return "-1" because no common prefix can be determined.

PLEASE ASSIGN ME THIS

### CODE REVIEW

**Comment by AnuragMishra358** [comment]
Screenshot 2024-10-18 090812
Screenshot 2024-10-18 090835
Screenshot 2024-10-18 090847

**Comment by Ayu-hack** [comment]
Please write file extension.

**Comment by Ayu-hack** [comment]
Please REF to README ONCE.

**Comment by Ayu-hack** [comment]
Closed due to no response

**Pull request closed without merging**
