### PR TITLE
Create Pairs with difference k(oct 30).py

### PR DESCRIPTION
**Pull request by Gokul-MK**
Create Pairs with difference k
problem of the day (oct 30)

### CODE REVIEW

**Comment by Gokul-MK** [comment]
@Ayu-hack 
Screenshot 2024-10-30 185038
 kindly review my PR and add hacktoberfest label

**Comment by Gokul-MK** [comment]
Screenshot 2024-10-30 194757

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on [GitHub](https://github.com/Ayu-hack) and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Pull request merged**
