### PR TITLE
Longest Common Prefix of Strings(gfg_31july_POTD)

### PR DESCRIPTION
**Pull request by stutimi**
gfgjuly31s
gfgjuly31q

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please add solutions in respective FOLDER

**Review by stutimi — COMMENTED** [review]
kindly assign me this

**Comment by Ayu-hack** [comment]
Nothing to be assigned. You need to add the file in respective folder

**Comment by Ayu-hack** [comment]
Please Ref
To add a file to an existing folder in your repository and create a pull request, follow these steps:

Navigate to the Folder:

Go to your repository on GitHub.
Navigate to the existing folder where you want to add the new file.
Add a New File:

Click on the "Add file" button located at the top right corner of the folder view.
Select "Create new file" from the dropdown menu.
In the "Name your file..." field, enter the name of your new file.
Add the content for your new file in the editor provided.
Commit the New File to a New Branch:

Scroll down to the "Commit new file" section below the editor.
Enter a commit message describing the addition of your new file.
Select the option "Create a new branch for this commit and start a pull request."
Enter a branch name for your changes.
Click on the "Propose new file" button to create the new branch and commit the file.
Create a Pull Request:

After proposing the new file, GitHub will redirect you to the "Open a pull request" page.
Verify the changes and ensure the base repository and branch are correct.
Enter a title and description for your pull request.
Click on the "Create pull request" button to open the pull request.

**Comment by stutimi** [comment]
> Please Ref To add a file to an existing folder in your repository and create a pull request, follow these steps:
> 
> Navigate to the Folder:
> 
> Go to your repository on GitHub. Navigate to the existing folder where you want to add the new file. Add a New File:
> 
> Click on the "Add file" button located at the top right corner of the folder view. Select "Create new file" from the dropdown menu. In the "Name your file..." field, enter the name of your new file. Add the content for your new file in the editor provided. Commit the New File to a New Branch:
> 
> Scroll down to the "Commit new file" section below the editor. Enter a commit message describing the addition of your new file. Select the option "Create a new branch for this commit and start a pull request." Enter a branch name for your changes. Click on the "Propose new file" button to create the new branch and commit the file. Create a Pull Request:
> 
> After proposing the new file, GitHub will redirect you to the "Open a pull request" page. Verify the changes and ensure the base repository and branch are correct. Enter a title and description for your pull request. Click on the "Create pull request" button to open the pull request.

ok thank you so much!

**Pull request closed without merging**
