### PR TITLE
Create Max sum path in two arrays(1st September).java

### PR DESCRIPTION
**Pull request by YogeshBabyOP**
An Optimal Greedy Solution

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot of working.

**Comment by YogeshBabyOP** [comment]
All Test Cases Passes!!

image

**Comment by Ayu-hack** [comment]
Great Work! 
Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on GitHub and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Pull request merged**
