### PR TITLE
Advanced Stock Predictor Dashboard

### PR DESCRIPTION
**Pull request by AdityaRoy999**
Screenshot 2024-10-14 133429

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Why you have added todo app code file ?

**Comment by Ayu-hack** [comment]
and you are adding to 2 different folders mini-project and project ai-ml folder. 
Please in one folder only

**Comment by AdityaRoy999** [comment]
please check now I have removed the unwanted files and corrected the PR.

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on [GitHub](https://github.com/Ayu-hack) and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Pull request merged**
