### PR TITLE
Added Kadane's Algorithm code

### PR DESCRIPTION
**Pull request by kjl98**
#Kadane's_Algorithm 

Kadane's Algorithm is a gem for solving the maximum subarray problem. It’s used to find the largest sum of a contiguous subarray within a one-dimensional numeric array. Think of it as hunting for the most profitable streak in a series of daily profits and losses.

How It Works:-
1] Initialize: Start by initializing two variables:

-> max_current to keep track of the maximum sum ending at the current position.

-> max_global to store the maximum sum found so far. Initially, max_current and max_global are set to the first element of the array.

2] Iterate Through the Array: Traverse the array from the second element to the end. For each element:

-> Update max_current to the maximum of the current element itself or the current element plus max_current.

-> Update max_global if max_current exceeds max_global.

3] Result: max_global will hold the maximum sum of the contiguous subarray by the end of the array traversal.

For the array [−2, 1, −3, 4, −1, 2, 1, −5, 4], Kadane's Algorithm would find the maximum sum subarray [4, −1, 2, 1], which sums up to 6.

*** Kadane’s Algorithm operates in O(n) time complexity, making it an efficient solution for large datasets.

kadane's

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot.

**Comment by Ayu-hack** [comment]
Please mention question and date of potd.

**Comment by Ayu-hack** [comment]
please comment in issue #14 so that I can assign you there

**Comment by Ayu-hack** [comment]
Please share the screenshot here.

**Comment by Ayu-hack** [comment]
Great Work! 
Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by kjl98** [comment]
Sir, please add the label - gssoc-extd 24
It's a humble request.

Regards @kjl98

**Comment by Ayu-hack** [comment]
THIS REPO IS NOT A PART OF GSSOC -EXTD 24. 
THIS REPO IS  A PART OF HACKTOBERFEST 24 ONLY .

**Comment by kjl98** [comment]
Okay sir, thank you for this.

**Comment by Ayu-hack** [comment]
if possible do follow on GitHub and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Pull request merged**
