### PR TITLE
Adding Stock Price Prediction using LSTM

### PR DESCRIPTION
**Pull request by YashviMehta03**
This AI/ML project performs stock price predictions in the following way :

- It takes features like open,high,low,adj close, roc, rsi,bollinger bands of 100 days and predicts the closing price of the next day.

- Features like roc, rsi, bollinger bands enhance the predictions by including non-conventional features

- In my output sample i have used the TCS Stock and provided two output graphs , one for the entire data and another for the test data

- It gives an accuracy score of around 0.95

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot of working

**Comment by YashviMehta03** [comment]
Should i attach the screenshot of output image in the comments here ?

**Comment by YashviMehta03** [comment]
TCS_stock_output_graph_on_entire_dataset
TCS_stock_output_graph_on_TEST_data

**Comment by YashviMehta03** [comment]
Let me know if anything else to be done

**Comment by Ayu-hack** [comment]
all good to merge now !

**Comment by Ayu-hack** [comment]
You can provide amazing projects and even solutions for GeeksforGeeks of previous months. It is will good for you and your GitHub profile will be boosted as well.

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on [GitHub](https://github.com/Ayu-hack) and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Pull request merged**
