### PR TITLE
Added Solution of POTD of July 1

### PR DESCRIPTION
**Pull request by bastenahamad**

### CODE REVIEW

**Comment by Ayu-hack** [comment]
buddy please comment in this issue #11 as well.

**Comment by Ayu-hack** [comment]
Please share the screenshot of working.

**Comment by bastenahamad** [comment]
> buddy please comment in this issue #11 as well.

okay sureee

**Comment by bastenahamad** [comment]
image
Working

**Comment by Ayu-hack** [comment]
if possible do follow on GitHub and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Pull request merged**
