### PR TITLE
password suggestor by vinnie

### PR DESCRIPTION
**Pull request by glider-vinnie**

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot of working

**Comment by glider-vinnie** [comment]
git

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on [GitHub](https://github.com/Ayu-hack) and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Pull request merged**
