### PR TITLE
Add random quote picker!

### PR DESCRIPTION
**Pull request by ats633**
Quote picker first project added.

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please the share screenshot

**Comment by ats633** [comment]
> Please the share screenshot

screenshot of code or of quote picker in the browser?

**Comment by ats633** [comment]
quotepicker in action

**Comment by Ayu-hack** [comment]
Great !
Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Pull request merged**
