### PR TITLE
Create Validate an IP Address(6th August).java

### PR DESCRIPTION
**Pull request by YogeshBabyOP**
Level  - medium
Approach - Naive

image

### CODE REVIEW

**Comment by Ayu-hack** [comment]
I cant merged multiple PRs at once. It will be considered as SPAM. please make PR in few interval of hour. 
Please try to understand.

**Comment by Ayu-hack** [comment]
Wait for sometime I will merge.

**Comment by YogeshBabyOP** [comment]
yeah ok I  can Understand

**Comment by Ayu-hack** [comment]
Great Work! 
Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on GitHub and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)! as a token of appreciation for the efforts! 🙌

**Pull request merged**
