### PR TITLE
Count Linked List Nodes Oct-14

### PR DESCRIPTION
**Pull request by AbhiKamp**
Done using python

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot.

**Comment by AbhiKamp** [comment]
Screenshot 2024-10-16 202100
Screenshot 2024-10-16 202517

**Comment by AbhiKamp** [comment]
Screenshot 2024-10-16 202517

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on [GitHub](https://github.com/Ayu-hack) and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Pull request merged**
