### PR TITLE
Health Tool: BMI Calculator

### PR DESCRIPTION
**Pull request by labishbardiya**
This project is a **BMI (Body Mass Index)** Calculator built using **Python** and **Tkinter**. It allows users to calculate their BMI based on their **height** (in meters) and **weight** (in kilograms). The application also categorizes the BMI result into various **health ranges** (Underweight, Normal, Overweight, and Obesity) and provides motivational messages for each category to encourage healthy living.

The tool features a user-friendly interface and includes options to reset input values and exit the application.

The project is complete to be used. Please add `hacktoberfest` and `good first issue` labels on it.

### CODE REVIEW

**Comment by labishbardiya** [comment]
Screenshot 2024-10-08 185408

**Comment by Ayu-hack** [comment]
Sorry you couldn't give you good first issue as you aren't first time contributor.

**Comment by Ayu-hack** [comment]
Great Work!
Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by labishbardiya** [comment]
> Sorry you couldn't give you good first issue as you aren't first time contributor.

I did the first contribution on `September 2024` repo > `Total Count(29th Sept).py`. I asked for `good first issue` label but you didn't gave me. Please can you give me that label on that, if possible it would be a great start for me.

**Comment by Ayu-hack** [comment]
Brother good first issue means you are first contributor on GitHub.

**Pull request merged**
