### PR TITLE
Solution Divisibility by 8 (28 Feb)

### PR DESCRIPTION
**Pull request by keikurono7**

### CODE REVIEW

**Comment by keikurono7** [comment]
Screenshot 2024-10-13 181005
for the feb problem

**Comment by Ayu-hack** [comment]
Please share the screenshot of GeeksforGeeks webpage and you have added two solutions in this PR. 
Please add only 1 solution and its respective code file and mention problem name along with date as title of PR.

**Comment by keikurono7** [comment]
Screenshot 2024-10-13 193126
I've removed the second file

**Comment by Ayu-hack** [comment]
Please add working side screenshot .

**Comment by keikurono7** [comment]
image

**Comment by Ayu-hack** [comment]
if possible do follow on [GitHub](https://github.com/Ayu-hack) and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Pull request merged**
