### PR TITLE
Added Study-Sync mini project

### PR DESCRIPTION
**Pull request by Kevish07**
Hey maintainer!
I have made this project after learning html and css,
I tried my best in this project and made it very responsive, I hope you like it and give it a chance.

Please, don't forget to merge this to your main branch and Provide this Hacktober and Hacktober-accepted label....

Thank you🙏

### CODE REVIEW

**Comment by Kevish07** [comment]
Screenshot 2024-10-20 at 10 35 03 PM
Screenshot 2024-10-20 at 10 35 17 PM
Screenshot 2024-10-20 at 10 35 31 PM

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on [GitHub](https://github.com/Ayu-hack) and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Comment by Kevish07** [comment]
Sure, Done !

**Pull request merged**
