### PR TITLE
single among triplet jan 4th solution

### PR DESCRIPTION
**Pull request by taneeshamadhu18**
Screenshot (103)

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Screenshot not uploaded.

**Comment by taneeshamadhu18** [comment]
It is

**Comment by taneeshamadhu18** [comment]
Screenshot (103)

**Comment by taneeshamadhu18** [comment]
now? is it seen?

**Comment by taneeshamadhu18** [comment]
I uploaded again.

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on [GitHub](https://github.com/Ayu-hack) and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Pull request merged**
