### PR TITLE
Solution Find the number of islands(6 oct POTD -GFG)

### PR DESCRIPTION
**Pull request by Anshuman7080**
This C++ code defines a class Solution that implements a depth-first search (DFS) algorithm to count the number of islands in a 2D grid, where '1' represents land and '0' represents water. The numIslands method iterates through the grid, incrementing a counter each time it finds a '1', and uses the DFS function to mark all connected land cells as '0'.

Kindly assign me this.

### CODE REVIEW

**Comment by Anshuman7080** [comment]
Screenshot 2024-10-13 181837
Screenshot 2024-10-13 181745
Screenshot 2024-10-13 181844

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
Please add solutions of previous month in which very less number of solution are there. In those you can add as many you want , it is good for you.

**Comment by Ayu-hack** [comment]
if possible do follow on GitHub and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Comment by Anshuman7080** [comment]
> Please add solutions of previous month in which very less number of solution are there. In those you can add as many you want , it is good for you.

Definitely, i will do .

**Comment by Anshuman7080** [comment]
> Great Work!  Merged. Thank you for contributing . Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄  👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

SURE.

**Comment by Anshuman7080** [comment]
> if possible do follow on [GitHub](https://github.com/Ayu-hack) and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

DONE

**Pull request merged**
