### PR TITLE
Create Single Number(18 oct 2024 gfg potd). C++

### PR DESCRIPTION
**Pull request by Mrdanish24**
Screenshot 2024-10-18 221616
Given an array arr[] of positive integers where every element appears even times except for one. Find that number occurring an odd number of times.

Examples:

Input: arr[] = [1, 1, 2, 2, 2]
Output: 2
Explanation: In the given array all element appear two times except 2 which appears thrice.

### CODE REVIEW

**Comment by Mrdanish24** [comment]
sir please assign this.

**Comment by Ayu-hack** [comment]
brother (.C++) is not correct extension. It will be (.cpp). 

**for your reference see this.**

Screenshot 2024-10-18 at 10 30 33 PM

**Comment by Mrdanish24** [comment]
sorry sir

**Comment by Mrdanish24** [comment]
sir have rectified my mistake

**Comment by Ayu-hack** [comment]
Brother you have added file extension in title. you need to add in file.

**Comment by Ayu-hack** [comment]
Please make new PR. Read rules in readme before creating PR

**Pull request closed without merging**
