### PR TITLE
Create GFG potd Solution today

### PR DESCRIPTION
**Pull request by Mrdanish24**
Given a permutation of some of the first natural numbers in an array arr[], determine if the array can be sorted in exactly two swaps. A swap can involve the same pair of indices twice.

Return true if it is possible to sort the array with exactly two swaps, otherwise return false.

Examples:

Input: arr = [4, 3, 2, 1]
Output: true
Explanation: First, swap arr[0] and arr[3]. The array becomes [1, 3, 2, 4]. Then, swap arr[1] and arr[2]. The array becomes [1, 2, 3, 4], which is sorted.

### CODE REVIEW

**Comment by Mrdanish24** [comment]
Initialize a counter that counts no of swaps.

2. check each element if it is placed in the right index i.e if 1 is at index 0 or in technical terms arr[i] == i-1.

3. if a element is misplaced then runa while loop that does the following:

check if the arr[i] == i+1 in each inter. i.e the while loop condition is until arr[i] != i+1.
we swap arr[i] and arr[arr[i]-1]
increment the counter.
check if counter is exceding 2. If yes return false.
4. After the loop is done we check if the cnt is 0(sorted already) or is 2. If true we return true.

5. Else we return false;

please assign me .



Screenshot 2024-10-16 184259

**Comment by Mrdanish24** [comment]
.

**Comment by Mrdanish24** [comment]
.

**Comment by Mrdanish24** [comment]
.

**Comment by Ayu-hack** [comment]
Please add in respective folder and add code ext.

**Pull request closed without merging**
