### PR TITLE
Added Potd solution for 27 September 2024

### PR DESCRIPTION
**Pull request by LeViiAcKerMan01**
Screenshot 2024-10-08 090442

Solution is working perfectly for all the test cases..

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please comment your solution named in relevant issue so that I can assign you. Then I can merge your PR.

**Comment by LeViiAcKerMan01** [comment]
> Please comment your solution named in relevant issue so that I can assign you. Then I can merge your PR.

Done i guess...now you can check for it..

**Comment by Ayu-hack** [comment]
Merged.
### Thank you for contributing .
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by LeViiAcKerMan01** [comment]
Thnc man...thnc alot ...

**Comment by LeViiAcKerMan01** [comment]
Hey @Ayu-hack , will i be creating an issue for each of the PR i made...? 
Thinking of contributing more to this repo...

**Comment by Ayu-hack** [comment]
yes you can but do it after sometimes

**Comment by Ayu-hack** [comment]
you dont need to create issue. Issues has been already created just choose from there and comment your solution name or project name and make PR.

**Comment by LeViiAcKerMan01** [comment]
> you dont need to create issue. Issues has been already created just choose from there and comment your solution name or project name and make PR.

Okk got it...

**Pull request merged**
