### PR TITLE
Audio Data Analysis using Python

### PR DESCRIPTION
**Pull request by dvamsidhar2002**
Hey! Ayush. 
I am adding codes related to a new topic I am working on Audio Data Analysis using Python. This is the beginning stage of my work where I am exploring the data analysis and preprocessing techniques of audio data. Very soon I will work on Machine Learning and Deep Learning projects related to audio data. I will add those files later. Consider the work and merge it if you like it.

Regards,
D Vamsidhar

### CODE REVIEW

**Comment by Ayu-hack** [comment]
brother you can share few working outputs

**Comment by Ayu-hack** [comment]
brother some output screenshot or processing screenshot

**Comment by dvamsidhar2002** [comment]
image

image

image

These are the screenshots regarding running the code

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by dvamsidhar2002** [comment]
Thanks a lot man.

**Pull request merged**
