### PR TITLE
23 Oct 24  GFG POTD sol.

### PR DESCRIPTION
**Pull request by thedarkking01**
@Ayu-hack Hii 😊

Problem solved : Find the Sum of Last N nodes of the Linked List

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot.

**Comment by thedarkking01** [comment]
pic: 
image

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on [GitHub](https://github.com/Ayu-hack) and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Pull request merged**
