### PR TITLE
Trained and Made a gradio interface

### PR DESCRIPTION
**Pull request by Nituhimani**
Trained with multiple machine learning model and find out their mean score error and r2 score in order to find the best model. Build a User friendly gradio interface to predict price.
Screenshot 2024-10-19 at 11 12 45 PM
Screenshot 2024-10-19 at 11 13 48 PM

### CODE REVIEW

**Comment by Ayu-hack** [comment]
what is the use of mean score error and r2 score here ?

**Comment by Nituhimani** [comment]
MSE is the average of the squares of the errors between the actual values and the predicted values.It quantifies how close the predictions are to the actual values.
R² is more about understanding how well your model explains the variability in the data.

**Comment by Nituhimani** [comment]
> what is the use of mean score error and r2 score here ?

It helps to find out the best model for our dataset.

**Comment by Ayu-hack** [comment]
Great Work!
 Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on [GitHub](https://github.com/Ayu-hack) and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Pull request merged**
