### PR TITLE
Added potd for 24 october issue#47

### PR DESCRIPTION
**Pull request by Nikhilsl12**
Hi have added the potd solution for the - Modify the Array problem for 24th october , i have also assigned under issue#47

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot.

**Comment by Nikhilsl12** [comment]
Screenshot (112)
Screenshot (114)

Here are the screenshots  of the code and potd.

**Comment by Ayu-hack** [comment]
remove solution of 25 oct. 
1 PR= 1 Solution

**Comment by Nikhilsl12** [comment]
> remove solution of 25 oct. 1 PR= 1 Solution

Ok

**Comment by Ayu-hack** [comment]
please provide solutions of previous months.

**Pull request closed without merging**
