### PR TITLE
Add january solution

### PR DESCRIPTION
**Pull request by taneeshamadhu18**
solution to Array Pair Divisibility.

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot.

**Comment by Ayu-hack** [comment]
Closed due to no response .

**Comment by taneeshamadhu18** [comment]
Heyy,
I'm so sorry 
I didn't see the message

**Comment by taneeshamadhu18** [comment]
Can I share the screenshot now

**Comment by Ayu-hack** [comment]
Please create new PR. **Read rules in readme before creating PR**

**Comment by taneeshamadhu18** [comment]
okk

**Pull request closed without merging**
