### PR TITLE
Added Solution to POTD for 12 September.

### PR DESCRIPTION
**Pull request by LeViiAcKerMan01**
Screenshot 2024-10-12 222146

The solution is working perfectly fine.

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Great Work! 
Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by LeViiAcKerMan01** [comment]
> Great Work!  Merged. Thank you for contributing . Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄  👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

Thnc man...really helped alot man ...looking forward to contribute to your repo only with some gud stuff next time..

**Comment by LeViiAcKerMan01** [comment]
> Great Work!  Merged. Thank you for contributing . Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄  👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

Please Accept the connection request on linkedin anyway...and github too!!

**Comment by Ayu-hack** [comment]
@LeViiAcKerMan01 brother I cant see your request on linkedin. May I know your name there ?

**Comment by LeViiAcKerMan01** [comment]
> @LeViiAcKerMan01 brother I cant see your request on linkedin. May I know your name there ?

Its by the name Priyanshu Tadhiyal. And you may see it tomorow as my account was on hibernation but i sent you a req i remember...!

**Comment by Ayu-hack** [comment]
okay buddy

**Pull request merged**
