### PR TITLE
Text-Summarizer created and added

### PR DESCRIPTION
**Pull request by Aishika3**
**Text Summarizer**
The PDF to Text Summarizer feature enables users to generate summaries from uploaded PDFs or text inputs. Developed with Streamlit and Python, it employs the txtai library for text summarization and PyPDF2 for efficient text extraction from PDFs.

**Installation to be done**
pip install streamlit
pip install txtai
pip install PyPDF2

added the screenshot of the above

Text-Summarizer

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Great Work! 
Merged.
Thank you for contributing .
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄 
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
if possible do follow on GitHub and connect on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) as a token of appreciation for the efforts! 🙌

**Comment by Ayu-hack** [comment]
you did a mistake you have added the file in project Ai/Ml folder but you were suppose to add in mini project!

**Comment by Aishika3** [comment]
But you assigned me in AI/ML project right?

**Comment by Ayu-hack** [comment]
yeah because you comment there !

**Pull request merged**
